# Generated by Django 5.2.5 on 2025-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_testimonial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
