# Generated by Django 5.2.5 on 2025-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
