# Generated by Django 5.2.5 on 2025-08-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertyCrud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('property_category', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_sub_heading', models.CharField(max_length=255)),
                ('property_desc', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('location_search', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
                ('completion_date', models.CharField(max_length=50)),
                ('payment_plan', models.CharField(max_length=50)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_gallery', models.ImageField(upload_to='properties/')),
                ('property_type_search', models.JSONField(default=list)),
                ('user_type', models.JSONField(default=list)),
                ('bedroom', models.JSONField(default=list)),
                ('bathroom', models.JSONField(default=list)),
                ('area', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='propertyCrud.propertycategory')),
            ],
        ),
    ]
