# Generated by Django 5.2.5 on 2025-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCrud', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycategory',
            name='developer',
            field=models.BooleanField(default=False),
        ),
    ]
