# Generated by Django 5.2.5 on 2025-08-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCrud', '0003_propertycategory_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location_search',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type_search',
        ),
        migrations.RemoveField(
            model_name='property',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_gallery',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
