# Generated by Django 5.2.5 on 2025-09-02 10:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCrud', '0004_remove_property_location_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_gallery',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
