# Generated by Django 5.2.5 on 2025-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCrud', '0005_alter_property_property_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
