# Generated by Django 5.2.5 on 2025-10-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCrud', '0007_property_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
