# Generated by Django 5.2.5 on 2025-10-17 07:35

from django.db import migrations
import uuid


def populate_uuids(apps, schema_editor):
    PropertyCategory = apps.get_model('propertyCrud', 'PropertyCategory')
    Property = apps.get_model('propertyCrud', 'Property')
    
    # Populate UUIDs for PropertyCategory records
    for category in PropertyCategory.objects.filter(uuid__isnull=True):
        category.uuid = uuid.uuid4()
        category.save(update_fields=['uuid'])
    
    # Populate UUIDs for Property records
    for property in Property.objects.filter(uuid__isnull=True):
        property.uuid = uuid.uuid4()
        property.save(update_fields=['uuid'])


def reverse_populate_uuids(apps, schema_editor):
    # This is a no-op since we don't want to remove UUIDs
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('propertyCrud', '0008_property_uuid_propertycategory_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_uuids, reverse_populate_uuids),
    ]
